set_property -dict {PACKAGE_PIN AB13 IOSTANDARD LVCMOS33} [get_ports a]
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD LVCMOS33} [get_ports b]
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVCMOS33} [get_ports cin]
set_property -dict {PACKAGE_PIN W11 IOSTANDARD LVCMOS33} [get_ports cout]
set_property -dict {PACKAGE_PIN W12 IOSTANDARD LVCMOS33} [get_ports s]