@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sat Apr 25 02:10:30 +0900 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 9b488732e2d445f5b0ded02240d79295 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot dff_presetclr_1_tb_behav xil_defaultlib.dff_presetclr_1_tb -log elaborate.log"
call xelab  -wto 9b488732e2d445f5b0ded02240d79295 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot dff_presetclr_1_tb_behav xil_defaultlib.dff_presetclr_1_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
